# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20160226_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='deneme'),
        ),
    ]
