"""
Django settings for tango_with_django_project project.

Generated by 'django-admin startproject' using Django 1.9.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'joih0)xu2fs(1c@in^i7qij%2#p93yk__aupokh!qbh%vcnbk6'

# SECURITY WARNING: don't run with debug turned on in production!

#DEBUG = False ---->>> burada eger projeyi dagıtacagımız zaman debug kısmının True olması pek saglıklı degilmis
#bunun ıcın Bu degeri false yapıyoruz ve
#from django.conf import settings
#from django.conf.urls.static import static iceri aktarıp
# projenin altındaki urls.py dosyasına if kalıbı koyulur. #etiket debug seklinde kayıtlı.
#ALLOWED_HOSTS kısmınıda eger localde calisiyorsak 127.0.0.1 yapmalyız !


DEBUG = True
ALLOWED_HOSTS = ["localhost"]

SESSION_EXPIRE_AT_BROWSER_CLOSE = True #Browser-length session ayarı -> Default degeri var eger kapatmak istiyorsan false degil yorum  satırı yap !


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rango',
    'blog',
    #'registration', #pip install django-registration-redux indirdik bunu eklemeden once.
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tango_with_django_project.urls'

TEMPLATE_PATH = os.path.join(BASE_DIR, 'templates')
######bu kısmı biz olusturduk. Templates dizinimizin yeri otamatik bulunsun diye.!!!
#ardından asagıdaki DIRS kısmına bu degiskenin adını verdik ki template lerimiz bulunsun.

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_PATH],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tango_with_django_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators
PASSWORD_HASHERS = (
'django.contrib.auth.hashers.PBKDF2PasswordHasher',
'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
)
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


LOGIN_URL = '/rango/login/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_PATH = os.path.join(BASE_DIR,'static') #static dosyamızın yolunu django ya bulduruyoruz.

STATIC_URL = '/static/'

#burada ise static dosyalarımızın yolunu django ya veriyoruz.

STATICFILES_DIRS = [
    STATIC_PATH,
]
